import GeoLayerDefinitionFunctions from '../../modules/geolayerdefinitionfunctions.js'
import {getMethods} from '../../modules/generic.js';
import {skl, map} from '../../modules/generic.js';


export default class GeoLayerDefinitions {
	constructor(map, arrayLayers = []) {
		this.gld = new GeoLayerDefinitionFunctions()
		this.maskstyle = new ol.style.Style({
		  fill: new ol.style.Fill({
			color: 'rgba(255,255,255,0.6)',
		  }),
		  stroke: new ol.style.Stroke({
			color: '#FF0000',
			width: 5,
		  }),
		});

	}
  
defineLayers() {
var ly_0000= new ol.layer.Vector({opacity: 0.6, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:maskerputten', '', '/wfs', map), visible: true, style: this.maskstyle});
var ly_0001= new ol.layer.Tile({title: 'OSM', visible: true, opacity: 0.6, projection: 'EPSG:3857', baseLayer: true, source: this.gld.srcOSM('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png')});
var ly_0002= new ol.layer.Tile({title: 'Top10NL', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, baseLayer: true, source: this.gld.srcPDOKWMTS('https://service.pdok.nl/brt/top10nl/wmts/v1_0', 'top10nl')});
var ly_0003= new ol.layer.Tile({title: 'BRT achtergrond standaard', visible: false, opacity: 0.6, minZoom: -Infinity, baseLayer: true, source: this.gld.srcPDOKWMTS('https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0', 'standaard')});
var ly_0004= new ol.layer.Tile({title: 'BRT achtergrond grijs', visible: false, opacity: 0.6, minZoom: -Infinity, baseLayer: true, source: this.gld.srcPDOKWMTS('https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0', 'grijs')});
var ly_0005= new ol.layer.Tile({title: 'BRT achtergrond pastel', visible: false, opacity: 0.6, minZoom: -Infinity, baseLayer: true, source: this.gld.srcPDOKWMTS('https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0', 'pastel')});
var ly_0006= new ol.layer.Vector({title: 'Gemeentegrens (V)', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://service.pdok.nl/', 'kadaster/bestuurlijkegebieden', 'bestuurlijkegebieden:Gemeentegebied', '/v1_0', '/wfs', map), baseLayer: true, style: style_gg});
function style_gg(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh6_8, 'stroke', 'Gemeentegrens (V)', 2, 0)};
var ly_0007= new ol.layer.Vector({title: 'Klompenpaden routes', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:Klompenpaden Routes', '', '/wfs', map), style: klompenpadenr_style, legendarubriek: 'NAAM'});
function klompenpadenr_style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh6_6, 'stroke', 'Klompenpaden routes', 5, 4)};
var ly_0008= new ol.layer.Vector({title: 'Klompenpaden punten', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:Klompenpaden punten', '', '/wfs', map), style: klompenpadenp_style, legendarubriek: 'type'});
function klompenpadenp_style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh5_11, 'point', 'Klompenpaden punten', 3, 4)};
var ly_0009= new ol.layer.Tile({title: 'LAW', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'wandelnet/landelijke-wandelroutes', 'landelijke-wandelroutes', '/v1_0', '/wms', map)});
var ly_0010= new ol.layer.Tile({title: 'Streekpaden', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'wandelnet/landelijke-wandelroutes', 'streekpaden', '/v1_0', '/wms', map)});
var ly_0011= new ol.layer.Vector({title: 'StaatsBosBeheer routes', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcArcGisWFSJSON('0SDFVmK1KedYIXHf','Wandelroutes_Staatsbosbeheer', 0, 'esrijson', map), style: style_sbbr, legendarubriek: 'Naam'});
function style_sbbr(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx8, 'stroke', 'StaatsBosBeheer routes', 3, 0)};
var ly_0012= new ol.layer.Tile({title: 'Fietsmap', visible: false, opacity: 0.6, projection: 'EPSG:3857', minZoom: -Infinity, source: this.gld.srcOSM('https://a.tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=aef8a5f1531a43a793897aecfabf4c2f')});
var ly_0013= new ol.layer.Tile({title: 'Fietsroutes', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcWMS('https://service.pdok.nl/', 'fietsplatform/landelijke-fietsroutes', 'landelijke-fietsroutes', '/v1_0', '/wms', map)});
var ly_0014= new ol.layer.Vector({title: 'Groen Erfgoed', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'landschapsatlas', 'landschapsatlas:groenerfgoed', '', '/wfs', map), style: style_la_groenerfgoed, legendarubriek: 'toponiem', textAttrName: 'toponiem', textMinZoom: 15});
function style_la_groenerfgoed(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs5_4, 'fill', 'Groen Erfgoed', 1, 0)};
var ly_0015= new ol.layer.Vector({title: 'Rijksmonumentaal groen', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 18.0, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'landschapsatlas', 'landschapsatlas:rijksmonumentaal_groen', '', '/wfs', map), style: style_la_rijksmonumentaalgroen, legendarubriek: 'categorie'});
function style_la_rijksmonumentaalgroen(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs5_1, 'fill', 'Rijksmonumentaal groen', 1, 0)};
var ly_0016= new ol.layer.Vector({title: 'Inheemse bomen en struiken', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 18.0, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'landschapsatlas', 'landschapsatlas:groenerfgoed_bomenstruiken_pnt', '', '/wfs', map), style: style_la_groenerfgoed_bomenstruiken_pnt, legendarubriek: 'nednaam', textAttrName: 'toponiem', textMinZoom: 14});
function style_la_groenerfgoed_bomenstruiken_pnt(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh5_1, 'point', 'Inheemse bomen en struiken', 4, 7)};
var ly_0017= new ol.layer.Tile({title: 'Monumentale bomen', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 18.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'landschapsatlas_view', 'monumentalebomen', '', '/wms', map)});
var ly_0018= new ol.layer.Tile({title: 'StaatsBosBeheer gebieden', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/0SDFVmK1KedYIXHf/arcgis/rest/services/Gebieden_2019/MapServer/WMTS', 'Gebieden_2019', [-285401.92,903401.92])});
var ly_0019= new ol.layer.Tile({title: 'Nat Beschermde gebieden', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'rvo/beschermde-gebieden/cdda', 'PS.ProtectedSite', '/v1_0', '/wms', map)});
var ly_0020= new ol.layer.Tile({title: 'Natura2000', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcWMS('https://service.pdok.nl/', 'rvo/beschermdegebieden/natura2000', 'PS.ProtectedSitesNatureConservation', '/v1_0', '/wms', map)});
var ly_0021= new ol.layer.Tile({title: 'Nationale landschappen', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'provincies/provinciaal-landschapsbeleid', 'PS.ProtectedSite', '/v1_0', '/wms', map)});
var ly_0022= new ol.layer.Tile({title: 'Natuurnetwerk Nederland', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'provincies/natuurnetwerk-nederland', 'PS.ProtectedSite', '/v1_0', '/wms', map)});
var ly_0023= new ol.layer.Tile({title: 'Geluidskaart wegen etmaal', visible: false, opacity: 0.6, minZoom: 13.0, source: this.gld.srcWMS('https://data.rivm.nl/geo/', 'alo', 'vw_rivm_r96_20170912_lg_rijksweg2016lden', '', '/wms', map)});
var ly_0024= new ol.layer.Tile({title: 'Geluidskaart spoorwegen etmaal', visible: false, opacity: 0.6, minZoom: 13.0, source: this.gld.srcWMS('https://data.rivm.nl/geo/', 'alo', 'vw_rivm_r94_20170912_lg_spoor2016lden', '', '/wms', map)});
var ly_0025= new ol.layer.Tile({title: 'Wet Ammoniak en Veehouderij gebieden', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'provincies/wet-ammoniak-veehouderij-gebieden', 'PS.ProtectedSite', '/v1_0', '/wms', map)});
var ly_0026= new ol.layer.Tile({title: 'Gewaspercelen', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcWMS('https://service.pdok.nl/', 'rvo/brpgewaspercelen', 'BrpGewas', '/v1_0', '/wms', map)});
var ly_0027= new ol.layer.Tile({title: 'Agrarisch Areaal', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcWMS('https://service.pdok.nl/', 'rvo/aan', 'aan', '/v1_0', '/wms', map)});
var ly_0028= new ol.layer.Vector({title: 'Routenetwerk 1650', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'verstedelijking', 'verstedelijking:nl_1650_route', '', '/wfs', map), style: style_rce_routenetw1650, legendarubriek: 'eigenaar'});
function style_rce_routenetw1650(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs2_1, 'stroke', 'Routenetwerk 1650', 4, 0)};
var ly_0029= new ol.layer.Vector({title: 'Routenetwerk 1575', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'verstedelijking', 'verstedelijking:NL1575_routenetwerk', '', '/wfs', map), style: style_rce_verst_routenetw1575, legendarubriek: 'eigenaar'});
function style_rce_verst_routenetw1575(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs3_1, 'stroke', 'Routenetwerk 1575', 4, 0)};
var ly_0030= new ol.layer.Tile({title: 'Verkeersongevallen 2021', visible: false, opacity: 0.6, minZoom: 13.0, source: this.gld.srcWMS('https://geo.rijkswaterstaat.nl/services/ogc/gdr/', 'verkeersongevallen_nederland_2020_2022', 'ongevallen_2020_2022', '', '/ows', map)});
var ly_0031= new ol.layer.Tile({title: 'Elektriciteitsnetten Onderstations', visible: false, opacity: 0.6, minZoom: 15.8, source: this.gld.srcWMS('https://service.pdok.nl/', 'liander/elektriciteitsnetten', 'onderstations', '/v1_0', '/wms', map)});
var ly_0032= new ol.layer.Tile({title: 'Elektriciteitsnetten Middenspannings Installaties', visible: false, opacity: 0.6, minZoom: 15.8, source: this.gld.srcWMS('https://service.pdok.nl/', 'liander/elektriciteitsnetten', 'middenspanningsinstallaties', '/v1_0', '/wms', map)});
var ly_0033= new ol.layer.Tile({title: 'Elektriciteitsnetten Hoogspanningskabels', visible: false, opacity: 0.6, minZoom: 15.8, source: this.gld.srcWMS('https://service.pdok.nl/', 'liander/elektriciteitsnetten', 'hoogspanningskabels', '/v1_0', '/wms', map)});
var ly_0034= new ol.layer.Tile({title: 'Elektriciteitsnetten Middenspanningskabels', visible: false, opacity: 0.6, minZoom: 15.8, source: this.gld.srcWMS('https://service.pdok.nl/', 'liander/elektriciteitsnetten', 'middenspanningskabels', '/v1_0', '/wms', map)});
var ly_0035= new ol.layer.Tile({title: 'Elektriciteitsnetten Laagspannings VerdeelKasten', visible: false, opacity: 0.6, minZoom: 15.8, source: this.gld.srcWMS('https://service.pdok.nl/', 'liander/elektriciteitsnetten', 'laagspanningsverdeelkasten', '/v1_0', '/wms', map)});
var ly_0036= new ol.layer.Tile({title: 'Elektriciteitsnetten Laagspanningkabels', visible: false, opacity: 0.6, minZoom: 14.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'liander/elektriciteitsnetten', 'laagspanningskabels', '/v1_0', '/wms', map)});
var ly_0037= new ol.layer.Tile({title: '1815', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1815/MapServer/WMTS', 'Historische_tijdreis_1815', [-30515500,31112399.999999993])});
var ly_0038= new ol.layer.Tile({title: '1850', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1850/MapServer/WMTS', 'Historische_tijdreis_1850', [-30515500,31112399.999999993])});
var ly_0039= new ol.layer.Tile({title: '1872', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1872/MapServer/WMTS', 'Historische_tijdreis_1872', [-30515500,31112399.999999993])});
var ly_0040= new ol.layer.Tile({title: '1892', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1892/MapServer/WMTS', 'Historische_tijdreis_1892', [-30515500,31112399.999999993])});
var ly_0041= new ol.layer.Tile({title: '1912', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1912/MapServer/WMTS', 'Historische_tijdreis_1912', [-30515500,31112399.999999993])});
var ly_0042= new ol.layer.Tile({title: '1932', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1932/MapServer/WMTS', 'Historische_tijdreis_1932', [-30515500,31112399.999999993])});
var ly_0043= new ol.layer.Tile({title: '1952', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1952/MapServer/WMTS', 'Historische_tijdreis_1952', [-30515500,31112399.999999993])});
var ly_0044= new ol.layer.Tile({title: '1962', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1962/MapServer/WMTS', 'Historische_tijdreis_1962', [-30515500,31112399.999999993])});
var ly_0045= new ol.layer.Tile({title: '1974', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1974/MapServer/WMTS', 'Historische_tijdreis_1974', [-30515500,31112399.999999993])});
var ly_0046= new ol.layer.Tile({title: '1986', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1986/MapServer/WMTS', 'Historische_tijdreis_1986', [-30515500,31112399.999999993])});
var ly_0047= new ol.layer.Tile({title: '1995', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1995/MapServer/WMTS', 'Historische_tijdreis_1995', [-30515500,31112399.999999993])});
var ly_0048= new ol.layer.Tile({title: '1999', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_1999/MapServer/WMTS', 'Historische_tijdreis_1999', [-30515500,31112399.999999993])});
var ly_0049= new ol.layer.Tile({title: '2006', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_2006/MapServer/WMTS', 'Historische_tijdreis_2006', [-30515500,31112399.999999993])});
var ly_0050= new ol.layer.Tile({title: '2009', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_2009/MapServer/WMTS', 'Historische_tijdreis_2009', [-30515500,31112399.999999993])});
var ly_0051= new ol.layer.Tile({title: '2012', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.4, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_2012/MapServer/WMTS', 'Historische_tijdreis_2012', [-30515500,31112399.999999993])});
var ly_0052= new ol.layer.Tile({title: 'Grondwaterspiegel GHG', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'bzk/bro-grondwaterspiegeldiepte', 'bro-grondwaterspiegeldieptemetingen-GHG', '/v1_0', '/wms', map)});
var ly_0053= new ol.layer.Tile({title: 'Grondwaterspiegel GLG', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'bzk/bro-grondwaterspiegeldiepte', 'bro-grondwaterspiegeldieptemetingen-GLG', '/v1_0', '/wms', map)});
var ly_0054= new ol.layer.Tile({title: 'Grondwaterspiegel GVG', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'bzk/bro-grondwaterspiegeldiepte', 'bro-grondwaterspiegeldieptemetingen-GVG', '/v1_0', '/wms', map)});
var ly_0055= new ol.layer.Tile({title: 'Grondwaterspiegel GT', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'bzk/bro-grondwaterspiegeldiepte', 'bro-grondwaterspiegeldieptemetingen-GT', '/v1_0', '/wms', map)});
var ly_0056= new ol.layer.Tile({title: 'Relieflijn', visible: false, opacity: 0.6, minZoom: 15.7, source: this.gld.srcWMS('https://service.pdok.nl/', 'brt/top10nl', 'relief', '/v1_0', '/wms', map)});
var ly_0057= new ol.layer.Tile({title: 'Hoogtelijn', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'brt/top10nl', 'hoogte', '/v1_0', '/wms', map)});
var ly_0058= new ol.layer.Tile({title: 'Actuele Hoogte Terrein', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'rws/ahn', 'dtm_05m', '/v1_0', '/wms', map)});
var ly_0059= new ol.layer.Tile({title: 'Actuele Hoogte Oppervlak', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'rws/ahn', 'dsm_05m', '/v1_0', '/wms', map)});
var ly_0060= new ol.layer.Tile({title: 'Geomorfologische kaart', visible: false, opacity: 0.6, minZoom: 13.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'bzk/bro-geomorfologischekaart', 'geomorphological_area', '/v2_0', '/wms', map)});
var ly_0061= new ol.layer.Tile({title: 'Bodemkaartcodes', visible: false, opacity: 0.6, minZoom: -Infinity, source: new ol.source.TileArcGISRest({url: 'https://atlas.brabant.nl/ArcGIS/rest/services/bodemwijzer_totaal_v2/MapServer/export?LAYERS=show%3A6'})});
var ly_0062= new ol.layer.Tile({title: 'Aardkundige waarde', visible: false, opacity: 0.6, minZoom: 12.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'provincies/aardkundige-waarden', 'PS.ProtectedSite', '/v1_0', '/wms', map)});
var ly_0063= new ol.layer.Tile({title: 'Bestand Bodemgebruik 2017', visible: false, opacity: 0.6, minZoom: 14.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'cbs/bestandbodemgebruik/2017', 'bestandbodemgebruik_2017_hoofdgroep', '/v1_0', '/wms', map)});
var ly_0064= new ol.layer.Vector({title: 'afgedekte Pleistoceen (V)', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'afgedekt_pleistoceen', 'afgedekt_pleistoceen:Afgedekt_Pleistoceen', '', '/wfs', map), style: afgedPleiststyle, legendarubriek: 'EERSTE_BOD'});
function afgedPleiststyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpC8_3, 'fill', 'afgedekte Pleistoceen (V)', 1, 0)};
var ly_0065= new ol.layer.Vector({title: 'Vergraven', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'verstoringsbronnen', 'verstoringsbronnen:vergraven_gr_sel', '', '/wfs', map), style: style_rce_vergraven, legendarubriek: 'leg_eenh_b'});
function style_rce_vergraven(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh3_2, 'fill', 'Vergraven', 1, 0)};
var ly_0066= new ol.layer.Vector({title: 'Ruilverkaveling', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://services.rce.geovoorziening.nl/', 'landschapsatlas', 'landschapsatlas:LandinrichtingNL', '', '/wfs', map), style: style_rce_ruilverkaveling, legendarubriek: 'labelnaam'});
function style_rce_ruilverkaveling(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs3_2, 'fill', 'Ruilverkaveling', 1, 0)};
var ly_0067= new ol.layer.Vector({title: 'Bodem Putten Hoofdklasse*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtenmainstyle, legendarubriek: 'main_soil_classification'});
function bodemputtenmainstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh0_8, 'fill', 'Bodem Putten Hoofdklasse*', 4, 0)};
var ly_0068= new ol.layer.Vector({title: 'Dikke eerdgronden*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtende, legendarubriek: 'soil_classification'});
function bodemputtende(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpde, 'fill', 'Dikke eerdgronden*', 4, 0, '', 'main_soil_classification','Dikke eerdgronden')};
var ly_0069= new ol.layer.Vector({title: 'Veengronden*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtenvg, legendarubriek: 'soil_classification'});
function bodemputtenvg(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpvg, 'fill', 'Veengronden*', 4, 0, '', 'main_soil_classification','Veengronden')};
var ly_0070= new ol.layer.Vector({title: 'Kalkloze zandgronden*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtenkzg, legendarubriek: 'soil_classification'});
function bodemputtenkzg(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpkzg, 'fill', 'Kalkloze zandgronden*', 4, 0, '', 'main_soil_classification','Kalkloze zandgronden')};
var ly_0071= new ol.layer.Vector({title: 'Podzolgronden*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtenpg, legendarubriek: 'soil_classification'});
function bodemputtenpg(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kppg, 'fill', 'Podzolgronden*', 4, 0, '', 'main_soil_classification','Podzolgronden')};
var ly_0072= new ol.layer.Vector({title: 'Zeekleigronden*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtenzg, legendarubriek: 'soil_classification'});
function bodemputtenzg(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpzg, 'fill', 'Zeekleigronden*', 4, 0, '', 'main_soil_classification','Zeekleigronden')};
var ly_0073= new ol.layer.Vector({title: 'Gedefinieerde associaties*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:bodem_putten', '', '/wfs', map), style: bodemputtenga, legendarubriek: 'soil_classification'});
function bodemputtenga(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpga, 'fill', 'Gedefinieerde associaties*', 4, 0, '', 'main_soil_classification','Gedefinieerde associaties')};
var ly_0074= new ol.layer.Tile({title: '1850 n Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie1850nc', '', '/wms', map)});
var ly_0075= new ol.layer.Tile({title: '1500 n Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie1500nc', '', '/wms', map)});
var ly_0076= new ol.layer.Tile({title: '1250 n Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie1250nc', '', '/wms', map)});
var ly_0077= new ol.layer.Tile({title: '800 n Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie800nc', '', '/wms', map)});
var ly_0078= new ol.layer.Tile({title: '100 n Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie100nc', '', '/wms', map)});
var ly_0079= new ol.layer.Tile({title: '250 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie250vc', '', '/wms', map)});
var ly_0080= new ol.layer.Tile({title: '500 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie500vc', '', '/wms', map)});
var ly_0081= new ol.layer.Tile({title: '1500 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie1500vc', '', '/wms', map)});
var ly_0082= new ol.layer.Tile({title: '2750 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie2750vc', '', '/wms', map)});
var ly_0083= new ol.layer.Tile({title: '3850 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie3850vc', '', '/wms', map)});
var ly_0084= new ol.layer.Tile({title: '5500 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie5500vc', '', '/wms', map)});
var ly_0085= new ol.layer.Tile({title: '9000 v Chr', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 17.0, source: this.gld.srcWMS('https://services.rce.geovoorziening.nl/', 'paleogeografischekaarten', 'paleogeografie9000vc', '', '/wms', map)});
var ly_0086= new ol.layer.Vector({title: 'PC6 gebieden', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcArcGisWFSJSON('nSZVuSZjHpEZZbRo','Postcodevlakken_PC6', 0, 'esrijson', map), style: pc6_style, legendarubriek: 'Naam'});
function pc6_style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh6_8, 'fill', 'PC6 gebieden', 3, 4)};
var ly_0087= new ol.layer.Tile({title: 'BAG pand', visible: false, opacity: 0.6, minZoom: 16.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'lv/bag', 'pand', '/v2_0', '/wms', map)});
var ly_0088= new ol.layer.Tile({title: 'BAG adressen', visible: false, opacity: 0.6, minZoom: 16.0, source: this.gld.srcWMS('https://service.pdok.nl/', 'lv/bag', 'verblijfsobject', '/v2_0', '/wms', map)});
var ly_0089= new ol.layer.Tile({title: 'Lufo 2006', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2006/MapServer/WMTS', 'Luchtfoto_2006', [-285401.92,903401.92])});
var ly_0090= new ol.layer.Tile({title: 'Lufo 2007', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2007/MapServer/WMTS', 'Luchtfoto_2007', [-285401.92,903401.92])});
var ly_0091= new ol.layer.Tile({title: 'Lufo 2008', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2008/MapServer/WMTS', 'Luchtfoto_2008', [-285401.92,903401.92])});
var ly_0092= new ol.layer.Tile({title: 'Lufo 2009', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2009/MapServer/WMTS', 'Luchtfoto_2009', [-285401.92,903401.92])});
var ly_0093= new ol.layer.Tile({title: 'Lufo 2010', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2010/MapServer/WMTS', 'Luchtfoto_2010', [-285401.92,903401.92])});
var ly_0094= new ol.layer.Tile({title: 'Lufo 2011', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2011/MapServer/WMTS', 'Luchtfoto_2011', [-285401.92,903401.92])});
var ly_0095= new ol.layer.Tile({title: 'Lufo 2012', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/LuchtfotoNL50cm_2012/MapServer/WMTS', 'LuchtfotoNL50cm_2012', [-285401.92,903401.92])});
var ly_0096= new ol.layer.Tile({title: 'Lufo 2013', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/LuchtfotoNL50cm_2013/MapServer/WMTS', 'LuchtfotoNL50cm_2013', [-285401.92,903401.92])});
var ly_0097= new ol.layer.Tile({title: 'Lufo 2014', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/LuchtfotoNL_50_cm_2014/MapServer/WMTS', 'LuchtfotoNL_50_cm_2014', [-285401.92,903401.92])});
var ly_0098= new ol.layer.Tile({title: 'Lufo 2015', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/LuchtfotoNL_2015_50_cm/MapServer/WMTS', 'LuchtfotoNL_2015_50_cm', [-285401.92,903401.92])});
var ly_0099= new ol.layer.Tile({title: 'Lufo 2016', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2016/MapServer/WMTS', 'Luchtfoto_2016', [-285401.92,903401.92])});
var ly_0100= new ol.layer.Tile({title: 'Lufo 2017', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2017/MapServer/WMTS', 'Luchtfoto_2017', [-285401.92,903401.92])});
var ly_0101= new ol.layer.Tile({title: 'Lufo 2018', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2018/MapServer/WMTS', 'Luchtfoto_2018', [-285401.92,903401.92])});
var ly_0102= new ol.layer.Tile({title: 'Lufo 2019', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2019/MapServer/WMTS', 'Luchtfoto_2019', [-285401.92,903401.92])});
var ly_0103= new ol.layer.Tile({title: 'Lufo 2020', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Luchtfoto_2020/MapServer/WMTS', 'Luchtfoto_2020', [-285401.92,903401.92])});
var ly_0104= new ol.layer.Tile({title: 'Lufo 2021', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcMapserverWMTS28992('https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/HR_Luchtfoto_2021/MapServer/WMTS', 'HR_Luchtfoto_2021', [-285401.92,903401.92])});
var ly_0105= new ol.layer.Tile({title: 'Lufo 2022', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcPDOKWMTS('https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0', '2022_ortho25')});
var ly_0106= new ol.layer.Tile({title: 'Lufo 2022 HR', visible: false, opacity: 0.6, minZoom: -Infinity, maxZoom: 19.5, source: this.gld.srcPDOKWMTS('https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0', '2022_orthoHR')});
var ly_0107= new ol.layer.Vector({title: 'Monument Percelen*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:monumentpercelen', '', '/wfs', map), style: puttenmonp_style, legendarubriek: 'rubriek', textAttrName: 'benaming', textMinZoom: 15});
function puttenmonp_style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh0_7, 'fill', 'Monument Percelen*', 3, 4)};
var ly_0108= new ol.layer.Vector({title: 'Monumenten*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:monumenten', '', '/wfs', map), style: puttenmon_style, legendarubriek: 'rubriek', textAttrName: 'benaming', textMinZoom: 15});
function puttenmon_style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs0_7, 'point', 'Monumenten*', 5, 8)};
var ly_0109= new ol.layer.Vector({title: 'Wildforstergoed Horne*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:wildforstersgoedHorne', '', '/wfs', map), style: wildforsterstyle, legendarubriek: 'Soort eigendom'});
function wildforsterstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh1_4, 'fill', 'Wildforstergoed Horne*', 1, 0)};
var ly_0110= new ol.layer.Vector({title: 'Perceelwijzigingen 1832 tov 1827*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadasterwijziging1832tov1827', '', '/wfs', map), style: style_k1832tov1827, legendarubriek: 'heeftToevoeging', textAttrName: 'kavel', textMinZoom: 15, declutter: true});
function style_k1832tov1827(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kp18322022, 'fill', 'Perceelwijzigingen 1832 tov 1827*', 1, 0)};
var ly_0111= new ol.layer.Vector({title: 'Adel*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_adel', '', '/wfs', map), style: style_k1832_adel, legendarubriek: 'naam_compleet', textAttrName: 'naam_compleet', textMinZoom: 15, declutter: true});
function style_k1832_adel(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh0_1, 'fill', 'Adel*', 1, 0)};
var ly_0112= new ol.layer.Vector({title: 'Bebouwd*', visible: false, opacity: 0.6, minZoom: 15.5, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_bebouwd', '', '/wfs', map), style: style_k1832_bebouwd, legendarubriek: 'Klasse gebouwd'});
function style_k1832_bebouwd(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh1_2, 'fill', 'Bebouwd*', 1, 0)};
var ly_0113= new ol.layer.Vector({title: 'Grootbezitters dorp*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_grootbezittersdorp', '', '/wfs', map), style: style_k1832_bezitdorp, legendarubriek: 'naam_compleet'});
function style_k1832_bezitdorp(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh3_2, 'fill', 'Grootbezitters dorp*', 1, 0)};
var ly_0114= new ol.layer.Vector({title: 'Ontgonnen grond classering*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_hoogsteclassering', '', '/wfs', map), style: style_k1832_classering, legendarubriek: 'hoogsteclassering'});
function style_k1832_classering(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpG6rood, 'fill', 'Ontgonnen grond classering*', 1, 0)};
var ly_0115= new ol.layer.Vector({title: 'Maalschappen*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_maalschappen', '', '/wfs', map), style: style_k1832_maalschappen, legendarubriek: 'naam_compleet', textAttrName: 'naam_compleet', textMinZoom: 14, declutter: true});
function style_k1832_maalschappen(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh4_1, 'fill', 'Maalschappen*', 1, 0)};
var ly_0116= new ol.layer.Vector({title: 'Kadastrale secties*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_secties', '', '/wfs', map), style: style_k1832_secties, legendarubriek: 'Sectie'});
function style_k1832_secties(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh5_1, 'fill', 'Kadastrale secties*', 1, 0)};
var ly_0117= new ol.layer.Vector({title: 'Soort eigendom*', visible: false, opacity: 0.6, minZoom: 14.8, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_soorteigendom', '', '/wfs', map), style: style_k1832_soorteigendom, legendarubriek: 'Soort eigendom hoofdrubriek'});
function style_k1832_soorteigendom(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kp1832, 'fill', 'Soort eigendom*', 1, 0)};
var ly_0118= new ol.layer.Vector({title: 'Wegen*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_wegencenterline_corrected', '', '/wfs', map), style: style_k1832_wegen, legendarubriek: 'Soort eigendom'});
function style_k1832_wegen(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCh4_3, 'stroke', 'Wegen*', 5, 0)};
var ly_0119= new ol.layer.Vector({title: 'Oude Route Putten Nijkerk*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_routeputtennijkerk', '', '/wfs', map), style: style_k1832_wegen, legendarubriek: 'Sectie'});
var ly_0120= new ol.layer.Vector({title: 'Kadastrale percelen*', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_single', '', '/wfs', map), style: style_k1832_percelen, legendarubriek: 'Sectie', textAttrName: 'kavel', textMinZoom: 16.5, declutter: true});
function style_k1832_percelen(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs5_2, 'fill', 'Kadastrale percelen*', 1, 0)};
var ly_0121= new ol.layer.Vector({title: 'Wegen 1832 vs 2022*', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:kadaster1832_wegen1832vs2022', '', '/wfs', map), style: style_k1832_wegen2022, legendarubriek: 'soort'});
function style_k1832_wegen2022(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kp18322022, 'stroke', 'Wegen 1832 vs 2022*', 4, 3)};
var ly_0122= new ol.layer.Vector({title: 'Terpen en doorbraken*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_terpenendoorbraken', '', '/wfs', map), style: terpstyle, legendarubriek: 'type'});
function terpstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs4_4, 'point', 'Terpen en doorbraken*', 1, 7)};
var ly_0123= new ol.layer.Vector({title: 'Voorland 1600*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_voorland1600', '', '/wfs', map), style: voorland1600style, legendarubriek: 'type'});
function voorland1600style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs1_4, 'fill', 'Voorland 1600*', 1, 0)};
var ly_0124= new ol.layer.Vector({title: 'Dijk 1600*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_dijk1600', '', '/wfs', map), style: dijk1600style, legendarubriek: 'type'});
function dijk1600style(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpG12blauw, 'stroke', 'Dijk 1600*', 4, 0)};
var ly_0125= new ol.layer.Vector({title: 'Stijghoogte grondwater*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_stijghoogtegrondwater', '', '/wfs', map), style: grwatstyle, legendarubriek: 'hoogte'});
function grwatstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpG12rood, 'stroke', 'Stijghoogte grondwater*', 3, 0)};
var ly_0126= new ol.layer.Vector({title: 'Bodem*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_bodem', '', '/wfs', map), style: bodemstyle, legendarubriek: 'type'});
function bodemstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs3_2, 'fill', 'Bodem*', 1, 0)};
var ly_0127= new ol.layer.Vector({title: 'Chloridegehalte*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_chloridegehalte', '', '/wfs', map), style: chloridestyle, legendarubriek: 'type'});
function chloridestyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpG6rood, 'fill', 'Chloridegehalte*', 1, 0)};
var ly_0128= new ol.layer.Vector({title: 'Geomorfologie*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:arkemheen_geomorfologie', '', '/wfs', map), style: geomstyle, legendarubriek: 'type'});
function geomstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpCs4_1, 'fill', 'Geomorfologie*', 1, 0)};
var ly_0129= new ol.layer.Vector({title: 'Gebouwen 1872*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:Kaart 1872', '', '/wfs', map), style: kfrisostyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function kfrisostyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx4, 'point', 'Gebouwen 1872*', 1, 7)};
var ly_0130= new ol.layer.Vector({title: 'J vd Kraats*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:J vd Kraats', '', '/wfs', map), style: jvdkstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function jvdkstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx3, 'point', 'J vd Kraats*', 1, 7)};
var ly_0131= new ol.layer.Vector({title: 'K Friso*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:KFriso', '', '/wfs', map), style: kfrisostyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
var ly_0132= new ol.layer.Vector({title: 'Vrij allodiaal goed*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Vrije allodiale deelbare goederen', '', '/wfs', map), style: allodiaalstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function allodiaalstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx2, 'point', 'Vrij allodiaal goed*', 1, 7)};
var ly_0133= new ol.layer.Vector({title: 'Leengoederen Hertog*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Leengoederen van de Hertog van Gelre', '', '/wfs', map), style: leengoedstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function leengoedstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx1, 'point', 'Leengoederen Hertog*', 1, 7)};
var ly_0134= new ol.layer.Vector({title: 'Boerderijen Herengoed*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Herengoed', '', '/wfs', map), style: pbhgstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbhgstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx11, 'point', 'Boerderijen Herengoed*', 1, 7)};
var ly_0135= new ol.layer.Vector({title: 'Boerderijen Wildforstergoed*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Wildforstersgoed', '', '/wfs', map), style: pbwfstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbwfstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx6, 'point', 'Boerderijen Wildforstergoed*', 1, 7)};
var ly_0136= new ol.layer.Vector({title: 'Boerderijen Van Putten*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Van Putten', '', '/wfs', map), style: pbpstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbpstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx8, 'point', 'Boerderijen Van Putten*', 1, 7)};
var ly_0137= new ol.layer.Vector({title: 'Boerderijen St Marie*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_St Marie', '', '/wfs', map), style: pbsmstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbsmstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx9, 'point', 'Boerderijen St Marie*', 1, 7)};
var ly_0138= new ol.layer.Vector({title: 'Boerderijen Jufferenstift Elten*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Jufferenstift Elten', '', '/wfs', map), style: pbjsstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbjsstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx10, 'point', 'Boerderijen Jufferenstift Elten*', 1, 7)};
var ly_0139= new ol.layer.Vector({title: 'Boerderijen Werden*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Werden', '', '/wfs', map), style: pbwstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbwstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx7, 'point', 'Boerderijen Werden*', 1, 7)};
var ly_0140= new ol.layer.Vector({title: 'Boerderijen Abdinckhof*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:boerderij1_Abdinckhof', '', '/wfs', map), style: pbabdstyle1, legendarubriek: 'Eigenaar', textAttrName: 'naam', textMinZoom: 14, declutter: true});
function pbabdstyle1(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx12, 'point', 'Boerderijen Abdinckhof*', 1, 7)};
var ly_0141= new ol.layer.Vector({title: 'Fotos*', visible: false, opacity: 0.6, minZoom: -Infinity, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:oudefotos3', '', '/wfs', map), style: fotosstyle, legendarubriek: 'Soort eigendom'});
function fotosstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx1, 'point', 'Fotos*', 1, 7)};
var ly_0142= new ol.layer.Vector({title: 'Straatnamen*', visible: false, opacity: 0.6, minZoom: 15.0, source: this.gld.srcOtherWFS('https://geo.geogemeente.nl:8443/geoserver/', 'GeoNetPutten', 'GeoNetPutten:straten', '', '/wfs', map), style: straatnamenstyle, legendarubriek: 'legenda'});
function straatnamenstyle(feature, resolution)  {return skl.maakstyle(map, feature, resolution, skl.kpfx1, 'stroke', 'Straatnamen*', 4, 0)};
var lg1= new ol.layer.Group({title: 'Achtergrondkaarten', fold: 'close', openInLayerSwitcher: true, layers: [ly_0001,ly_0002,ly_0003,ly_0004,ly_0005,ly_0006]})
var lg2= new ol.layer.Group({title: 'Landbouw', fold: 'close', openInLayerSwitcher: true, layers: [ly_0025,ly_0026,ly_0027]})
var lg3= new ol.layer.Group({title: 'Milieu', fold: 'close', openInLayerSwitcher: true, layers: [ly_0023,ly_0024]})
var lg5= new ol.layer.Group({title: 'Bodem door de eeuwen', fold: 'close', openInLayerSwitcher: true, layers: [ly_0074,ly_0075,ly_0076,ly_0077,ly_0078,ly_0079,ly_0080,ly_0081,ly_0082,ly_0083,ly_0084,ly_0085]})
var lg6= new ol.layer.Group({title: 'Bodem overig', fold: 'close', openInLayerSwitcher: true, layers: [ly_0060,ly_0061,ly_0062,ly_0063,ly_0064,ly_0065,ly_0066]})
var lg7= new ol.layer.Group({title: 'Hoogte', fold: 'close', openInLayerSwitcher: true, layers: [ly_0056,ly_0057,ly_0058,ly_0059]})
var lg8= new ol.layer.Group({title: 'Putten bodem', fold: 'close', openInLayerSwitcher: true, layers: [ly_0067,ly_0068,ly_0069,ly_0070,ly_0071,ly_0072,ly_0073]})
var lg9= new ol.layer.Group({title: 'Water', fold: 'close', openInLayerSwitcher: true, layers: [ly_0052,ly_0053,ly_0054,ly_0055]})
var lg10= new ol.layer.Group({title: 'Verkeer', fold: 'close', openInLayerSwitcher: true, layers: [ly_0028,ly_0029,ly_0030]})
var lg11= new ol.layer.Group({title: 'Arkemheen', fold: 'close', openInLayerSwitcher: true, layers: [ly_0122,ly_0123,ly_0124,ly_0125,ly_0126,ly_0127,ly_0128]})
var lg12= new ol.layer.Group({title: 'Kadaster 1832', fold: 'close', openInLayerSwitcher: true, layers: [ly_0109,ly_0110,ly_0111,ly_0112,ly_0113,ly_0114,ly_0115,ly_0116,ly_0117,ly_0118,ly_0119,ly_0120,ly_0121]})
var lg13= new ol.layer.Group({title: 'Klooster goed ed', fold: 'close', openInLayerSwitcher: true, layers: [ly_0129,ly_0130,ly_0131,ly_0132,ly_0133,ly_0134,ly_0135,ly_0136,ly_0137,ly_0138,ly_0139,ly_0140]})
var lg14= new ol.layer.Group({title: 'Putten Monumenten', fold: 'close', openInLayerSwitcher: true, layers: [ly_0107,ly_0108]})
var lg15= new ol.layer.Group({title: 'Putten algemeen', fold: 'close', openInLayerSwitcher: true, layers: [ly_0141,ly_0142]})
var lg16= new ol.layer.Group({title: 'Luchtfotos', fold: 'close', openInLayerSwitcher: true, layers: [ly_0089,ly_0090,ly_0091,ly_0092,ly_0093,ly_0094,ly_0095,ly_0096,ly_0097,ly_0098,ly_0099,ly_0100,ly_0101,ly_0102,ly_0103,ly_0104,ly_0105,ly_0106]})
var lg17= new ol.layer.Group({title: '1815-1900', fold: 'close', openInLayerSwitcher: true, layers: [ly_0037,ly_0038,ly_0039,ly_0040]})
var lg18= new ol.layer.Group({title: '1912-1965', fold: 'close', openInLayerSwitcher: true, layers: [ly_0041,ly_0042,ly_0043,ly_0044]})
var lg19= new ol.layer.Group({title: '1974-1999', fold: 'close', openInLayerSwitcher: true, layers: [ly_0045,ly_0046,ly_0047,ly_0048]})
var lg20= new ol.layer.Group({title: '2000-2012', fold: 'close', openInLayerSwitcher: true, layers: [ly_0049,ly_0050,ly_0051]})
var lg21= new ol.layer.Group({title: 'Elektriciteit', fold: 'close', openInLayerSwitcher: true, layers: [ly_0031,ly_0032,ly_0033,ly_0034,ly_0035,ly_0036]})
var lg22= new ol.layer.Group({title: 'Fietsen', fold: 'close', openInLayerSwitcher: true, layers: [ly_0012,ly_0013]})
var lg23= new ol.layer.Group({title: 'Natuur', fold: 'close', openInLayerSwitcher: true, layers: [ly_0014,ly_0015,ly_0016,ly_0017,ly_0018,ly_0019,ly_0020,ly_0021,ly_0022]})
var lg24= new ol.layer.Group({title: 'Wandelen', fold: 'close', openInLayerSwitcher: true, layers: [ly_0007,ly_0008,ly_0009,ly_0010,ly_0011]})
var lg25= new ol.layer.Group({title: 'Bodem', fold: 'close', openInLayerSwitcher: true, layers: [lg5,lg6,lg7,lg8,lg9]})
var lg27= new ol.layer.Group({title: 'Putten', fold: 'close', openInLayerSwitcher: true, layers: [lg11,lg12,lg13,lg14,lg15]})
var lg28= new ol.layer.Group({title: 'Registraties en Lufo', fold: 'close', openInLayerSwitcher: true, layers: [lg16,ly_0086,ly_0087,ly_0088]})
var lg29= new ol.layer.Group({title: 'Topotijdreis', fold: 'close', openInLayerSwitcher: true, layers: [lg17,lg18,lg19,lg20]})
var lg30= new ol.layer.Group({title: 'Infra', fold: 'close', openInLayerSwitcher: true, layers: [lg21]})
var lg31= new ol.layer.Group({title: 'Recreatie', fold: 'close', openInLayerSwitcher: true, layers: [lg22,lg23,lg24]})
var lg32= new ol.layer.Group({title: 'Historie', fold: 'close', openInLayerSwitcher: true, layers: [lg29]})
var lg33= new ol.layer.Group({title: 'Infra en Verkeer', fold: 'close', openInLayerSwitcher: true, layers: [lg30,lg10]})
var lg34= new ol.layer.Group({title: 'Natuur & Recreatie', fold: 'close', openInLayerSwitcher: true, layers: [lg31]})
var lgs = [lg1,lg28,lg3,lg2,lg33,lg32,lg25,lg27]

		return [lgs, ly_0000]
	}
}